version: "3.9"

services:
  nextapp:
    container_name: t3git
    # image: ct3a-docker
    environment:
      - DATABASE_URL=postgres://postgres:postgres@t3git-postgres:5432/
    build: .
    ports:
      - "3000:3000"
  postgres:
    container_name: t3git-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=public
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
