import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";
import { type NextPage } from "next";
import { useTheme } from "next-themes";
import { RouterOutputs, api } from "~/utils/api";

const SingleProfilePage: NextPage = () => {
  const { isLoaded: userLoaded, isSignedIn } = useUser();
  api.post.getAll.useQuery();

   if (!userLoaded) return <div />;

  const { setTheme } = useTheme();

  return (
    <>
      <Head>
        <title>T3 Git</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-spacing-2 border-x border-slate-400 md:max-w-3xl">
          <div>Profile View</div>
        </div>
      </main>
    </>
  );
}

export default SingleProfilePage;