import Head from "next/head";
import { type NextPage } from "next";

const SinglePostPage: NextPage = () => {
  
  return (
    <>
      <Head>
        <title>T3 Git</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-spacing-2 border-x border-slate-400 md:max-w-3xl">
          <div>Post View</div>
        </div>
      </main>
    </>
  );
};

export default SinglePostPage;
